apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"longhorn","app.kubernetes.io/name":"longhorn","app.kubernetes.io/version":"v1.5.3"},"name":"longhorn-driver-deployer","namespace":"longhorn-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"longhorn-driver-deployer"}},"template":{"metadata":{"labels":{"app":"longhorn-driver-deployer","app.kubernetes.io/instance":"longhorn","app.kubernetes.io/name":"longhorn","app.kubernetes.io/version":"v1.5.3"}},"spec":{"containers":[{"command":["longhorn-manager","-d","deploy-driver","--manager-image","longhornio/longhorn-manager:v1.5.3","--manager-url","http://longhorn-backend:9500/v1"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"SERVICE_ACCOUNT","valueFrom":{"fieldRef":{"fieldPath":"spec.serviceAccountName"}}},{"name":"CSI_ATTACHER_IMAGE","value":"longhornio/csi-attacher:v4.2.0"},{"name":"CSI_PROVISIONER_IMAGE","value":"longhornio/csi-provisioner:v3.4.1"},{"name":"CSI_NODE_DRIVER_REGISTRAR_IMAGE","value":"longhornio/csi-node-driver-registrar:v2.7.0"},{"name":"CSI_RESIZER_IMAGE","value":"longhornio/csi-resizer:v1.7.0"},{"name":"CSI_SNAPSHOTTER_IMAGE","value":"longhornio/csi-snapshotter:v6.2.1"},{"name":"CSI_LIVENESS_PROBE_IMAGE","value":"longhornio/livenessprobe:v2.9.0"}],"image":"longhornio/longhorn-manager:v1.5.3","imagePullPolicy":"IfNotPresent","name":"longhorn-driver-deployer"}],"initContainers":[{"command":["sh","-c","while [ $(curl -m 1 -s -o /dev/null -w \"%{http_code}\" http://longhorn-backend:9500/v1) != \"200\" ]; do echo waiting; sleep 2; done"],"image":"longhornio/longhorn-manager:v1.5.3","name":"wait-longhorn-manager"}],"securityContext":{"runAsUser":0},"serviceAccountName":"longhorn-service-account"}}}}
  creationTimestamp: "2025-11-03T01:38:53Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.5.3
  name: longhorn-driver-deployer
  namespace: longhorn-system
  resourceVersion: "474658"
  uid: 4c32b531-3e1b-41d7-82cf-e3c0afaef18a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: longhorn-driver-deployer
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/version: v1.5.3
    spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - deploy-driver
        - --manager-image
        - longhornio/longhorn-manager:v1.5.3
        - --manager-url
        - http://longhorn-backend:9500/v1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CSI_ATTACHER_IMAGE
          value: longhornio/csi-attacher:v4.2.0
        - name: CSI_PROVISIONER_IMAGE
          value: longhornio/csi-provisioner:v3.4.1
        - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
          value: longhornio/csi-node-driver-registrar:v2.7.0
        - name: CSI_RESIZER_IMAGE
          value: longhornio/csi-resizer:v1.7.0
        - name: CSI_SNAPSHOTTER_IMAGE
          value: longhornio/csi-snapshotter:v6.2.1
        - name: CSI_LIVENESS_PROBE_IMAGE
          value: longhornio/livenessprobe:v2.9.0
        image: longhornio/longhorn-manager:v1.5.3
        imagePullPolicy: IfNotPresent
        name: longhorn-driver-deployer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1)
          != "200" ]; do echo waiting; sleep 2; done
        image: longhornio/longhorn-manager:v1.5.3
        imagePullPolicy: IfNotPresent
        name: wait-longhorn-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-03T01:38:53Z"
    lastUpdateTime: "2025-11-03T01:39:30Z"
    message: ReplicaSet "longhorn-driver-deployer-68d455f5f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-04T00:36:29Z"
    lastUpdateTime: "2025-11-04T00:36:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
