---
# MariaDB Data PVC (Longhorn)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi  # 20Gi → 3Gi
---
# Nextcloud App PVC (Longhorn)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi  # 10Gi → 2Gi
---
# Nextcloud User Data PVC (Longhorn)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi  # 100Gi → 3Gi
