apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
stringData:
  # MariaDB 비밀번호
  mysql-root-password: rootpassword
  mysql-password: wlalspassword
  mysql-user: nextcloud
  mysql-database: nextcloud