---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-user
        - name: MYSQL_HOST
          value: "nextcloud-db"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "192.168.1.187 localhost"
        volumeMounts:
        - name: nextcloud-app
          mountPath: /var/www/html
        - name: nextcloud-data
          mountPath: /var/www/html/data
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /status.php
            port: 80
            httpHeaders:
            - name: Host
              value: "192.168.1.187"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
            httpHeaders:
            - name: Host
              value: "192.168.1.187"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: nextcloud-app
        persistentVolumeClaim:
          claimName: nextcloud-app-pvc
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
      # nodeSelector 삭제됨
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30888
    protocol: TCP
    name: http
  selector:
    app: nextcloud  # selector 빠진 부분 추가
